services:
  app:
    image: spring-demo:latest
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

volumes:
  pgdata-dev:
